const words = [
    "1",
    "1one",
    "1two",
    "1three",
    "1four",
    "1five",
    "1six",
    "1seven",
    "1eight",
    "1nine",
    "1ten",
    "1eleven",
    "1twelve",
    "1thirteen",
    "1fourteen",
    "1fifteen",
    "1sixteen",
    "1seventeen",
    "1eighteen",
    "1nineteen",
    "1twenty",
    "1twenty one",
    "1twenty two",
    "1twenty three",
    "1twenty four",
    "1twenty five",
    "1twenty six",
    "1twenty seven",
    "1twenty eight",
    "1twenty nine",
    "1thirty",
    "1thirty one",
    "1thirty two",
    "1thirty three",
    "1thirty four",
    "1thirty five",
    "1thirty six",
    "1thirty seven",
    "1thirty eight",
    "1thirty nine",
    "1forty",
    "1forty one",
    "1forty two",
    "1forty three",
    "1forty four",
    "1forty five",
    "1forty six",
    "1forty seven",
    "1forty eight",
    "1forty nine",
    "1fifty",
    "1fifty one",
    "1fifty two",
    "1fifty three",
    "1fifty four",
    "1fifty five",
    "1fifty six",
    "1fifty seven",
    "1fifty eight",
    "1fifty nine",
    "1sixty",
    "1sixty one",
    "1sixty two",
    "1sixty three",
    "1sixty four",
    "1sixty five",
    "1sixty six",
    "1sixty seven",
    "1sixty eight",
    "1sixty nine",
    "1seventy",
    "1seventy one",
    "1seventy two",
    "1seventy three",
    "1seventy four",
    "1seventy five",
    "1seventy six",
    "1seventy seven",
    "1seventy eight",
    "1seventy nine",
    "1eighty",
    "1eighty one",
    "1eighty two",
    "1eighty three",
    "1eighty four",
    "1eighty five",
    "1eighty six",
    "1eighty seven",
    "1eighty eight",
    "1eighty nine",
    "1ninety",
    "1ninety one",
    "1ninety two",
    "1ninety three",
    "1ninety four",
    "1ninety five",
    "1ninety six",
    "1ninety seven",
    "1ninety eight",
    "1ninety nine",
];
